
services:
  - type: web
    name: my-app
    env: 
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /
    autoDeploy: true
    domains:
      - my-app.onrender.com
